version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  mqtt-logger:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo

